export const AUTHENTICATE_LOCAL="AUTHENTICATE_LOCAL";
export const AUTHENTICATE_GOOGLE="AUTHENTICATE_GOOGLE";
export const AUTHENTICATE_FACEBOOK="AUTHENTICATE_FACEBOOK";
export const AUTHENTICATE_LINKEDIN="AUTHENTICATE_LINKEDIN";
export const FETCH_USER_DATA="FETCH_USER_DATA";
export const FETCH_AUTHENTICATION_STATUS="FETCH_AUTHENTICATION_STATUS";